export const JDE_STATUS_MAP: Record<string, string> = {
  // 05 PRP Order, Pre-Quote Accept
  "05": "PRP Order, Pre-Quote Accept",

  // Purchasing Activities (100-499)
  "100": "Enter Purchase Requisition",
  "110": "Approved/MRP Requisition",
  "120": "Print Purchase Requisition",
  "130": "Generate PO from Requisition",
  "132": "SDS Req to Whse",
  "134": "SDS Req to PO",
  "140": "Enter Request for Bid/Quote",
  "160": "Print Request for Bid/Quote",
  "161": "Send EDI Request for Quote",
  "180": "Enter Supplier Bid",
  "200": "Print Bid/Quote Confirmation",
  "210": "Enter Blanket Purchase Order",
  "215": "Release Blanket Order",
  "216": "Preliminary Order Created",
  "220": "Enter Purchase Order",
  "225": "Rejected Order",
  "230": "Approval Process",
  "240": "Print Purchase Order Proof",
  "245": "Awaiting Acknowledgement",
  "250": "Approve Shipment/Load",
  "260": "Approve Purchase Order Proof",
  "280": "Print Purchase Order",
  "281": "Send EDI Purchase Order",
  "282": "Receive EDI PO Acknowledgment",
  "300": "Record Supplier Acknowledgement",
  "320": "Enter Change Order",
  "325": "Order Revised by Ack.",
  "340": "Approve Change Order",
  "360": "Print Change Order",
  "361": "Send EDI Purchase Order Change",
  "362": "Receive EDI Change Ack.",
  "370": "Record Supplier Shipment",
  "380": "Print Purchase Receiver",
  "381": "Application Certificate",
  "400": "Record Purchase Receipt",
  "410": "Back Ordered",
  "420": "Release from Inspection",
  "425": "Freight, Insurance & Expenses Brazil Purchasing",
  "430": "Close Nota Fiscal Brazil Purchasing",
  "440": "Record Matching Voucher",
  "499": "Canceled Line",

  // Selling Activities (500-625)
  "500": "Enter Quote/Blanket Order",
  "515": "Release Quote/Blanket to Order",
  "520": "Enter Order/Receive EDI Order",
  "521": "Review EDI/Uploaded Order",
  "522": "Correct EDI Order",
  "523": "Send EDI Change Acknowledgement",
  "524": "In Fulfillment",
  "525": "Print Acknowledgement / Send EDI",
  "527": "Approve Shipment/Load",
  "530": "Work Order Created",
  "535": "In Warehouse",
  "536": "Approve Shipment",
  "537": "Print Control Pick",
  "540": "Print Pick",
  "542": "Print Loading Note ECS",
  "545": "Pick Confirmation",
  "550": "Print Shipping Documents",
  "555": "Pack Confirmation",
  "559": "Waiting Purchase Order Receipt",
  "560": "Ship Confirmation",
  "561": "Send EDI Response to RFQ",
  "562": "Print Packing List/Invoice",
  "563": "Print Packing List/Invoice",
  "564": "Delivery Document Selection ECS",
  "565": "Print Delivery Notes",
  "570": "Print Bill of Lading",
  "571": "Send EDI Advanced Ship Notice",
  "572": "Receive EDI Receiving Advice",
  "573": "Delivery Confirm ECS",
  "574": "Normal Generate XML Brazil",
  "575": "Cycle Billing",
  "576": "Send EDI Advanced Ship Notice",
  "577": "Receive EDI Receiving Advice",
  "578": "EDI Receiving Advice Reject",
  "579": "Pending Revenue Recognition",
  "580": "Print Invoices",
  "581": "Send EDI Invoice",
  "585": "Print Interbranch Invoice",
  "590": "Print Pre-Invoice Proof",
  "595": "Generate Nota Fiscal Brazil Sales",
  "597": "Freight, Insurance & Expenses Brazil Sales",
  "598": "Print Nota Fiscal Brazil Sales",
  "600": "Invoice Journal",
  "610": "Print G/L Sales Recap-Detail",
  "615": "Print G/L Sales Recap-Summary",
  "617": "Generate Tax Lines Brazil Sales",
  "620": "Sales Update",
  "625": "End of Month Repricing ECS",

  // Direct Ship & Special (800+)
  "800": "Direct Ship Acknowledgement",
  "810": "Print Sales Invoice",
  "831": "Invoice Error Argentina",
  "832": "Shipment Note Error Argentina",

  // Backorder codes (900)
  "900": "Backorder in S/O Entry (Do Not Change or Delete)",
  "902": "Backorder in Commitments (Do Not Change or Delete)",
  "904": "Backorder in Ship. Conf. (Do Not Change or Delete)",
  "909": "Backorder in Transportation (Do Not Change or Delete ECS)",

  // Added codes (910-926)
  "910": "Added in Price Adjustments (Do Not Change or Delete)",
  "912": "Added in Commitments (Do Not Change or Delete)",
  "913": "Added in Pick Confirmation (Do Not Change or Delete)",
  "914": "Added in Ship. Conf. (Do Not Change or Delete)",
  "915": "Added as Replacement Item (Do Not Change or Delete)",
  "916": "Added as Subst/Associated Item (Do Not Change or Delete)",
  "917": "Added as Promotional Item (Do Not Change or Delete)",
  "918": "Added in Transpo Arrange Import (Do Not Change or Delete)",
  "919": "Added in Transportation (Do Not Change or Delete ECS)",
  "920": "Added in Order Repricing (Do Not Change or Delete)",
  "922": "Added in Work Order Generation (Do Not Change or Delete)",
  "924": "Added in Freight Update (Do Not Change or Delete)",
  "925": "Added in Transpo Confirm Import (Do Not Change or Delete)",
  "926": "Added in Fulfillment Release (Do Not Change or Delete)",

  // Canceled codes (980-998)
  "980": "Canceled in Order Entry (Do Not Change or Delete)",
  "981": "Canceled in Fulfillment Release (Do Not Change or Delete)",
  "982": "Canceled in Commitments (Do Not Change or Delete)",
  "983": "Canceled in Pick Confirmation (Do Not Change or Delete)",
  "984": "Canceled in Ship. Conf. (Do Not Change or Delete)",
  "985": "Canceled by Replacement (Do Not Change or Delete)",
  "986": "Canceled by Substitution (Do Not Change or Delete)",
  "987": "Canceled by Price Recalc. (Do Not Change or Delete)",
  "988": "Canceled in Update (Do Not Change or Delete)",
  "989": "Canceled in Transportation (Do Not Change or Delete ECS)",
  "990": "Cancelled by Promotional Item (Do Not Change or Delete)",
  "991": "Cancelled due to BOM",
  "995": "Unapproved Load (Do Not Change or Delete)",
  "996": "Cancelled Nota Fiscal (Do Not Change or Delete)",
  "997": "Cancelled Nota Fiscal after Run (Do Not Change or Delete)",
  "998": "Reversed Nota Fiscal Brazil",
  "999": "Complete - Ready to Purge"
};

export const getStatusVariant = (code: string): "default" | "secondary" | "outline" | "destructive" => {
  const num = parseInt(code);
  if (num >= 900) return "destructive"; // Cancelled/Backorder
  if (num >= 500) return "default"; // Selling/Invoicing
  if (num >= 400) return "secondary"; // Receipt/Complete
  if (num >= 100) return "outline"; // Pending/PO
  return "secondary";
};

export const getStatusLabel = (code: string): string => JDE_STATUS_MAP[code] || code;

